### ISSUE TITLE
how to visualise the outputed mesh?

### ISSUE THREAD

**Issue by ForrestPi** [aashishrai3799/3DFaceCAM#6]
Hi, could you provide the script how to render the mesh to a video like [[Project Page]](https://aashishrai3799.github.io/3DFaceCAM)

**Comment by Zerg-Overmind** [comment]
Hi, thanks for the interest. You may render the mesh by [MeshLab](https://www.meshlab.net/),  store as images and use function cv2.VideoWriter (from python package cv2) to make a video with a fps you like.
